environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --network-timeout 600000

test_script:
  - node index.js --version

cache:
  - node_modules -> yarn.lock

build: off
